# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Synthetic Data Vault
tagline: Open Source tools for Synthetic Data Generation
description: >-
  The Synthetic Data Vault (SDV) enables end users to easily generate synthetic data for
  different data modalities, including single table, relational and time series data. With
  this ecosystem, we are releasing several years of our work building, testing and evaluating
  algorithms and models geared towards synthetic data generation.
email: info@sdv.dev
logo: /assets/logo.png
keywords: mit, dai, open, source, open source, synthetic, data, generation, sdv, vault
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sdv.dev" # the base hostname & protocol for your site, e.g. http://example.com
basegithub: "https://github.com/sdv-dev"

slack: https://join.slack.com/t/sdv-space/shared_invite/zt-gdsfcb5w-0QQpFMVoyB2Yd6SRiMplcw

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: The Synthetic Data Vault
      tagline: >-
        Open Source tools for Synthetic Data Generation
      description: >-
        The Synthetic Data Vault (SDV) enables end users to easily generate synthetic data for
        different data modalities, including single table, relational and time series data. With
        this ecosystem, we are releasing several years of our work building, testing and evaluating
        algorithms and models geared towards synthetic data generation.
      keywords: mit, dai, open, source, open source, synthetic, data, generation, sdv, vault

twitter:
  username: sdv_dev
  card: summary

social:
  links:
    - https://twitter.com/sdv_dev
    - https://slack.sdv.dev
    - https://github.com/sdv-dev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  #- jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
