name: Build and Deploy SDV Blog

on:
  push:
    branches:
      - gatsby-home
  repository_dispatch:
    branches:
      - gatsby-home
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.HOME_TOKEN }}
          deploy-branch: gh-pages-home

        env: 
          SITEURL: "https://sdv.dev"
          SITEPATH: ""