name: Build and Deploy sdv dev

on:
  push:
    branches:
      - gatsby-home
  repository_dispatch:
    branches:
      - gatsby-home
  workflow_dispatch:
    branches:
      - gatsby-home
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.HOME_TOKEN }}
          deploy-branch: gh-pages-home
        env:
          SITEURL: "https://sdv.dev"
          SITEPATH: ""
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
